Project.COREMVC/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Project.BLL.Managers.Abstracts;
using Project.CONF.Configutaion;
using Project.COREMVC.Areas.Admin.Models.PageVms.Category;
using Project.COREMVC.Areas.Admin.Models.PageVms.EntityAttribute;
using Project.COREMVC.Areas.Admin.Models.PageVms.Product;
using Project.COREMVC.Areas.Admin.Models.PureVms.Category;
using Project.COREMVC.Areas.Admin.Models.PureVms.EntityAttribute;
using Project.COREMVC.Areas.Admin.Models.PureVms.Product;
using Project.COREMVC.Models.PageVms.Product;
using Project.COREMVC.Models.PureVms.Products;
using Project.COREMVC.Models.ShoppingTools;
using Project.ENTITIES.Models;


namespace Project.COREMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class ProductController : Controller
    {
        readonly IProductManager _productManager;
        readonly ICategoryManager _categoryManager;
       

        public ProductController(IProductManager productManager, ICategoryManager categoryManager)
        {
            _productManager = productManager;
            _categoryManager = categoryManager;
            
        }

        public IActionResult GetProducts()
        {
            List<Product> products = _productManager.GetActives();
          

            List<ProductPureVm> pureVms = products.Select(pureVms => new ProductPureVm
            {
                ID = pureVms.ID,
                ProductName = pureVms.ProductName,
                UnitPrice = pureVms.UnitPrice,
                UnitsInStock = pureVms.UnitsInStock,
                Status = pureVms.Status,
                ImagePath = pureVms.ImagePath,
                CategoryName = pureVms.Category.CategoryName,


                

            }).ToList();
            

            ProductPageVm pageVm = new ProductPageVm();
            pageVm.ProductPureVms = pureVms;

            return View(pageVm);

            
        }
        
        public IActionResult CreateProduct()
        {
          

            List<Category> categories = _categoryManager.GetActives();

            List<CategoryProductPureVm> categoryProductPureVm = categories.Select(c => new CategoryProductPureVm
            {
                ID = c.ID,
                CategoryName = c.CategoryName
               
            }).ToList();

            CreateProductPageVm cppVm = new CreateProductPageVm()
            {
                CategoryProductPureVms = categoryProductPureVm
            };

            return View(cppVm);

        }
        [HttpPost]
        public IActionResult CreateProduct(CreateProductPageVm createProductPageVm, IFormFile formFile)
        {


            
            if (formFile != null )
            {
                Guid uniqueName = Guid.NewGuid();
                string extension = Path.GetExtension(formFile.FileName); //dosyanın uzantısını ele gecirdik...
                createProductPageVm.CreateProductPureVm.ImagePath = $"/images/{uniqueName}{extension}";
                //Bulunduğunuz konuma göre mevcut konumu alır 
                string path = $"{Directory.GetCurrentDirectory()}/wwwroot{createProductPageVm.CreateProductPureVm.ImagePath}";
                FileStream stream = new(path, FileMode.Create);
                formFile.CopyTo(stream);
            }
            else
            {
                createProductPageVm.CreateProductPureVm.ImagePath = "/OuterImages/DenemeFoto.png";
            }

           
          

            Product p = new Product()
            {
                ProductName = createProductPageVm.CreateProductPureVm.ProductName,
                ImagePath = createProductPageVm.CreateProductPureVm.ImagePath,
                UnitPrice = createProductPageVm.CreateProductPureVm.UnitPrice,
                CategoryID = createProductPageVm.CreateProductPureVm.CategoryID,
                UnitsInStock = createProductPageVm.CreateProductPureVm.UnitsInStock,
                
            };

            _productManager.Add(p);

            TempData["message"] = $"{p.ProductName} isimli ürün eklenmiştir";
            return RedirectToAction("GetProducts");


        }
           

        


        public async Task<IActionResult> DeleteProduct(int id)
        {
            _productManager.Delete(await _productManager.FindAsync(id));
            return RedirectToAction("GetProducts");
        }

        public async  Task<IActionResult> DestroyProduct(int id)
        {
            TempData["message"] = _productManager.Destroy(await _productManager.FindAsync(id));
            return RedirectToAction("GetProducts");
        }

        public async Task<IActionResult> UpdateProduct(int id)
        {

            Product p = await _productManager.FindAsync(id);

            

            UpdateProductPureVm updateProductPureVm = new UpdateProductPureVm()
            {
                ID = p.ID,
                ProductName = p.ProductName,
                ImagePath = p.ImagePath,
                UnitPrice = p.UnitPrice,
                UnitsInStock= p.UnitsInStock,
                CategoryID = p.Category.ID
                
               
            };

            List<Category> categories = _categoryManager.GetActives();

            List<CategoryProductPureVm> categoryProductPureVm = categories.Select(c => new CategoryProductPureVm
            {
                ID = c.ID,
                CategoryName = c.CategoryName
                

            }).ToList();

            UpdateProductPageVm upPageVm = new UpdateProductPageVm()
            {
                CategoryProductPureVms = categoryProductPureVm,
                UpdateProductPureVm = updateProductPureVm
                
            };

            return View(upPageVm);

        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct(UpdateProductPageVm updateProductPageVm, IFormFile formFile)
        {
            if (formFile != null)
            {
                Guid uniqueName = Guid.NewGuid();
                string extension = Path.GetExtension(formFile.FileName); //dosyanın uzantısını ele gecirdik...
                updateProductPageVm.UpdateProductPureVm.ImagePath = $"/images/{uniqueName}{extension}";
                //Bulunduğunuz konuma göre mevcut konumu alır 
                string path = $"{Directory.GetCurrentDirectory()}/wwwroot{updateProductPageVm.UpdateProductPureVm.ImagePath}";
                FileStream stream = new(path, FileMode.Create);
                formFile.CopyTo(stream);
            }
            
            Product p = new()
            {
                    ID = updateProductPageVm.UpdateProductPureVm.ID,
                    ProductName = updateProductPageVm.UpdateProductPureVm.ProductName,
                    ImagePath = updateProductPageVm.UpdateProductPureVm.ImagePath,
                    UnitPrice = updateProductPageVm.UpdateProductPureVm.UnitPrice,
                    CategoryID = updateProductPageVm.UpdateProductPureVm.CategoryID,
                    UnitsInStock = updateProductPageVm.UpdateProductPureVm.UnitsInStock

            };
                TempData["message"] = $"{p.ProductName} isimli veri güncellenmiştir";
                await _productManager.UpdateAsync(p);
                return RedirectToAction("GetProducts");
            

        }



       
       




    }

}

Project.COREMVC/Controllers/ShoppingController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Project.BLL.Managers.Abstracts;
using Project.COMMON.Tools;
using Project.COREMVC.Areas.Admin.Models.PureVms.Category;
using Project.COREMVC.Areas.Admin.Models.PureVms.Product;
using Project.COREMVC.Models.PageVms.AppUsers;
using Project.COREMVC.Models.PageVms.OrderPageVm;
using Project.COREMVC.Models.PageVms.Product;
using Project.COREMVC.Models.PageVms.Shopping;
using Project.COREMVC.Models.PureVms.AppUsers;
using Project.COREMVC.Models.PureVms.Attribute;
using Project.COREMVC.Models.PureVms.OrderDetails;
using Project.COREMVC.Models.PureVms.Orders;
using Project.COREMVC.Models.PureVms.Products;
using Project.COREMVC.Models.PureVms.Shoppings;
using Project.COREMVC.Models.SessionServices;
using Project.COREMVC.Models.ShoppingTools;
using Project.ENTITIES.Models;
using System.Linq;
using System.Text;
using X.PagedList;

namespace Project.COREMVC.Controllers
{
    public class ShoppingController : Controller
    {
        readonly IProductManager _productManager;
        readonly ICategoryManager _categoryManager;
        readonly IOrderManager _orderManager;
        readonly IOrderDetailManager _orderDetailManager;
        readonly UserManager<AppUser> _userManager;
        readonly IHttpClientFactory _httpClientFactory;
        readonly IEntityAttributeProductManager _entityAttributeProductManager;
        readonly IEntityAttributeManager _entityAttributeManager;
        public ShoppingController(IProductManager productManager, ICategoryManager categoryManager, IOrderManager orderManager, IOrderDetailManager orderDetailManager, UserManager<AppUser> userManager, IHttpClientFactory httpClientFactory, IEntityAttributeProductManager entityAttributeProductManager, IEntityAttributeManager entityAttributeManager)
        {
            _productManager = productManager;
            _categoryManager = categoryManager;
            _orderManager = orderManager;
            _orderDetailManager = orderDetailManager;
            _userManager = userManager;
            _httpClientFactory = httpClientFactory;
            _entityAttributeProductManager = entityAttributeProductManager;
            _entityAttributeManager = entityAttributeManager;
        }

        public IActionResult Index(int? page, int? categoryID)
        {

            List<Category> categories = _categoryManager.GetActives();

            List<CategoryForShoppingPureVm> cPureVm = categories.Select(cPureVm => new CategoryForShoppingPureVm
            {
                ID = cPureVm.ID,
                CategoryName = cPureVm.CategoryName

            }).ToList();

            List<Product> products = _productManager.GetActives();

            IPagedList<ProductForShoppingPureVm> pPureVm = products.Select(pPureVm => new ProductForShoppingPureVm
            {
                ID = pPureVm.ID,
                ProductName = pPureVm.ProductName,
                UnitPrice = pPureVm.UnitPrice,
                UnitsInStock = pPureVm.UnitsInStock,
                ImagePath = pPureVm.ImagePath,
                CategoryName = pPureVm.Category.CategoryName,
                CategoryID = pPureVm.Category.ID

            }).ToPagedList();



            ShoppingPageVm sPageVm = new ShoppingPageVm();


            sPageVm.ProductForShoppingPureVms = categoryID == null ? pPureVm.ToPagedList(page ?? 1, 5) : pPureVm.Where(x => x.CategoryID == categoryID).ToPagedList(page ?? 1, 5);

            sPageVm.CategoryForShoppingPureVms = cPureVm;



            if (categoryID != null)
            {
                TempData["catID"] = categoryID;
            }




            return View(sPageVm);
        }

       
        public async Task<IActionResult> AddToCart(int id)
        {
            // Burada kısacası sepet varsa onu kullan yoksa yeniden yarat
            Cart c = GetCartFromSession("scart") == null ? new Cart() : GetCartFromSession("scart");
            CartPageVm cartPageVm = new CartPageVm();
            cartPageVm.Cart = c;


            Product productToBeAdded = await _productManager.FindAsync(id);
            ProductForShoppingPureVm pPureVm = new()
            {
                ID = productToBeAdded.ID,
                ProductName = productToBeAdded.ProductName,
                UnitPrice = productToBeAdded.UnitPrice,
                
                CategoryID = productToBeAdded.Category.ID,
                CategoryName = productToBeAdded.Category.CategoryName,
                ImagePath = productToBeAdded.ImagePath

            };


            CartItem ci = new()
            {
                ID = pPureVm.ID,
                ProductName = pPureVm.ProductName,
                UnitPrice = pPureVm.UnitPrice,
                ImagePath = pPureVm.ImagePath,
                CategoryName = pPureVm.CategoryName,
                CategoryID = pPureVm.CategoryID
            };

            cartPageVm.Cart.AddToCart(ci);


            SetCartForSession(cartPageVm.Cart);

            TempData["message"] = $"{ci.ProductName} isimli ürün sepete eklenmiştir";

            return RedirectToAction("Index", new { productToBeAdded.CategoryID });
        }

        // Bu metottada sepeti session'a eklemiş bulnmaktayız
        void SetCartForSession(Cart c)
        {
            HttpContext.Session.SetObject("scart", c);
        }

        // Cart nesnesi session da var mı yok mu onu kontrol etmesi için bu geriye değer döndüren metotu yarattık
        Cart GetCartFromSession(string key)
        {
            return HttpContext.Session.GetObject<Cart>(key);
        }


        public IActionResult CartPage()
        {
            if (GetCartFromSession("scart") == null)
            {
                TempData["message"] = "Sepetiniz su anda bos";
                return RedirectToAction("Index");
            }


            Cart c = GetCartFromSession("scart");

            CartPageVm cartPageVm = new CartPageVm();
            cartPageVm.Cart = c;
            return View(cartPageVm); 
        }


        public IActionResult DeleteFromCart(int id)
        {
            if (GetCartFromSession("scart") != null)
            {
                Cart c = GetCartFromSession("scart");


                CartPageVm cartPageVm = new CartPageVm();
                cartPageVm.Cart = c;


               cartPageVm.Cart.RemoveFromCart(id);
                SetCartForSession(cartPageVm.Cart);
                ControlCart(cartPageVm.Cart);
            }
            return RedirectToAction("CartPage");
        }

        //Cart'ın içerisindeki ürünler sıfırsa Cart'ı direkt sil
        void ControlCart(Cart c)
        {
            if (c.GetCartItems.Count == 0) HttpContext.Session.Remove("scart");
        }

        public IActionResult DecreaseFromCart(int id)
        {

            if (GetCartFromSession("scart") != null)
            {
                Cart c = GetCartFromSession("scart");
                CartPageVm cartPageVm= new CartPageVm();
                cartPageVm.Cart = c;
                cartPageVm.Cart.Decrease(id);
                SetCartForSession(cartPageVm.Cart);
                ControlCart(cartPageVm.Cart);
            }

            return RedirectToAction("CartPage");
        }
     
        public IActionResult ConfirmOrder()
        {
            return View();
        }
        [HttpPost]
        public async  Task<IActionResult> ConfirmOrder(OrderRequestPageVm orPageVm)
        {

         
            
            Cart c = GetCartFromSession("scart");
            CartPageVm cartPageVm = new CartPageVm();
            cartPageVm.Cart = c;


            orPageVm.OrderPureVm.PriceOfOrder = orPageVm.PaymentRequestPureVm.ShoppingPrice = cartPageVm.Cart.TotalPrice;


             //http://localhost:5118/

            HttpClient client = _httpClientFactory.CreateClient();
            string jsonData = JsonConvert.SerializeObject(orPageVm.PaymentRequestPureVm);
            StringContent content =new StringContent(jsonData, Encoding.UTF8,"application/json");
           HttpResponseMessage responseMessage =  await client.PostAsync("http://localhost:5118/api/Transaction", content);


            if (responseMessage.IsSuccessStatusCode)
            {
                if (User.Identity.IsAuthenticated)
                {
                    AppUser appUser = await _userManager.FindByNameAsync(User.Identity.Name);

                    orPageVm.OrderPureVm.AppUserID = appUser.Id;
                    orPageVm.OrderPureVm.Email = appUser.Email;
                    orPageVm.OrderPureVm.NameDescription = appUser.UserName;

                }

                Order order = new()
                {
                    Email = orPageVm.OrderPureVm.Email,
                    NameDescription = orPageVm.OrderPureVm.NameDescription,
                    AppUserID = orPageVm.OrderPureVm.AppUserID,
                    PriceOfOrder = orPageVm.OrderPureVm.PriceOfOrder,
                    ShippingAddress = orPageVm.OrderPureVm.ShippingAddress,
                    ID = orPageVm.OrderPureVm.ID
                };
                await _orderManager.AddAsync(order);

                
                string urunIsimleri = "";
                decimal ürünToplamFiyat = 0;
                foreach (CartItem item in cartPageVm.Cart.GetCartItems)
                {
                    OrderDetail orderDetail = new()
                    {
                        OrderID = order.ID,
                        ProductID = item.ID,
                        Quantity = item.Amount,
                        UnitPrice = item.UnitPrice
                    };

                    Product product = await _productManager.FindAsync(item.ID);
                        product.UnitsInStock -= item.Amount;
                    await _productManager.UpdateAsync(product);

                    await _orderDetailManager.AddAsync(orderDetail);
                    urunIsimleri += $" {item.ProductName} x{item.Amount} tane,";
                    

Project.COREMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="icon" href="~/OuterImages/Favicon.png">
    
   

    <title>Uygun Al Member and Visitor Template</title>

    <!-- Bootstrap core CSS -->
    <link href="~/OuterTools/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/OuterTools/css/bootstrap-reset.css" rel="stylesheet">

    <!--external css-->
    <link href="~/OuterTools/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/OuterTools/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="~/OuterTools/css/owl.carousel.css" type="text/css">

    <!-- Inline CSS for custom styles -->
    <style>
        .detail-attr-list {
            display: flex;
            flex-wrap: wrap;
           
            padding: 0;
            margin: 0;
        }

            .detail-attr-list li {
                margin-bottom: 5px; /* Liste elemanları arasında boşluk bırakır */
                padding-bottom: 5px; /* Alt kenarlık ile iç boşluk oluşturur */
                border-bottom: 1px solid #ccc; /* Alt kenarlık */
                width: 48%; /* Her iki öğeden sonra bir satıra sığacak şekilde genişlik ayarla */
                box-sizing: border-box;
                background-color: #F2F2F2;
            }

                .detail-attr-list li:nth-child(2n) {
                    margin-right: 0; /* İkinci öğeden sonra sağ boşluğu kaldır */
                }

                .detail-attr-list li:nth-child(2n+1) {
                    margin-right: 4%; /* İlk öğenin sağında boşluk bırak */
                }

              

            .detail-attr-list b {
                font-weight: bold;
                color: #333; /* Yazı rengi */
                margin-right: 20px; /* Sağ tarafa 20px boşluk bırakır */
            }
    </style>
    <!-- Custom styles for this template -->
    <link href="~/OuterTools/css/style.css" rel="stylesheet">
    <link href="~/OuterTools/css/style-responsive.css" rel="stylesheet" />

    <a href="~/lib/jquery/dist/jquery.min.map">~/lib/jquery/dist/jquery.min.map</a>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    





    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <section id="container">
        <!--header start-->
        <header class="header white-bg" style="top: -1px;">
            <div class="sidebar-toggle-box">
                <div data-original-title="Toggle Navigation" data-placement="right" class="icon-reorder tooltips"></div>
            </div>
            <!--logo start--> 
            <a asp-action="Index" asp-controller="Shopping" class="logo">Uygun<span>Al</span></a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
                <!--  notification start -->
                <ul class="nav top-menu">
                    
                </ul>
                <!--  notification end -->
            </div>
            <div class="top-nav ">
                <!--search & user info start-->
                <ul class="nav pull-right top-menu">
                   
                    <!-- user login dropdown start-->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <img alt="" src="~/OuterImages/AnonimFoto.jpg">
                            <span class="username">@(User.Identity.Name ?? "Kullanıcı") </span>
                            <b class="caret"></b>
                        </a>


                        <ul class="dropdown-menu extended logout">
                            <div class="log-arrow-up"></div>
                            @RenderSection("Sepet", false)
                            @if (User.Identity.Name != null)
                            {
                                <li><a asp-action="Logout" asp-controller="Home"> <i class="icon-key"></i> Log Out</a></li>
                            }
                            else
                            {
                                <li><a asp-action="SignIn" asp-controller="Home"> <i class="icon-key"></i> Sign in</a></li>
                            }

                        </ul>


                    </li>
                    <!-- user login dropdown end -->
                </ul>
                <!--search & user info end-->
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->

        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <li>
                        <a asp-action="Index" asp-controller="Shopping">
                            <i class="icon-home"></i>
                            <span>Ana sayfa</span>
                        </a>
                    </li>

                    
                    <li>
                        <a asp-action="MailPanel" asp-controller="Home">
                            <i class="icon-envelope"></i>
                            <span>Mail </span>
                            
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Shopping" asp-action="CartPage">
                            <i class="icon-shopping-cart"></i>
                            <span>Sepet</span>
                           @*  <span class="label label-danger pull-right mail-info"></span> *@
                        </a>
                    </li>
                    
                    <li>
                        <a asp-action="Register" asp-controller="Home">
                            <i class="icon-user"></i>
                            <span>Kayıt ol</span>
                        </a>
                    </li>
                    <li>
                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-area="Admin" asp-action="GetProducts" asp-controller="Product">
                                <i class="icon-dashboard"></i>
                                <span>Admin Sayfası</span>
                            </a>
                        }
                        
                    </li>

                   
                    <!--multi level menu end-->

                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
               
              @RenderBody()

            </section>
        </section>
        <!--main content end-->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                2024 &copy; UygunAl by VectorLab.
                <a href="#" class="go-top">
                    <i class="icon-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/OuterTools/js/jquery.js"></script>
    <script src="~/OuterTools/js/jquery-1.8.3.min.js"></script>
    <script src="~/OuterTools/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/OuterTools/js/jquery.scrollTo.min.js"></script>
    <script src="~/OuterTools/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/OuterTools/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="~/OuterTools/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="~/OuterTools/js/owl.carousel.js"></script>
    <script src="~/OuterTools/js/jquery.customSelect.min.js"></script>
    <script src="~/OuterTools/js/respond.min.js"></script>

    <script class="include" type="text/javascript" src="~/OuterTools/js/jquery.dcjqaccordion.2.7.js"></script>

    <!--common script for all pages-->
    <script src="~/OuterTools/js/common-scripts.js"></script>

    <!--script for this page-->
    <script src="~/OuterTools/js/sparkline-chart.js"></script>
    <script src="~/OuterTools/js/easy-pie-chart.js"></script>
    <script src="~/OuterTools/js/count.js"></script>

    <script>

        //owl carousel

        $(document).ready(function() {
            $("#owl-demo").owlCarousel({
                navigation : true,
                slideSpeed : 300,
                paginationSpeed : 400,
                singleItem : true,
                autoPlay:true

            });
        });

        //custom select box

        $(function(){
            $('select.styled').customSelect();
        });

    </script>

</body>
</html>