Project.COREMVC/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Project.BLL.Managers.Abstracts;

namespace Project.COREMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        readonly IOrderManager _orderManager;

        public OrderController(IOrderManager orderManager)
        {
            _orderManager = orderManager;
        }

        public IActionResult Index()
        {
            return View(_orderManager.GetAll());
        }
    }
}

Project.COREMVC/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project.COREMVC.Areas.Admin.Models.PageVms.AppRole;
using Project.COREMVC.Areas.Admin.Models.PureVms.AppRole;
using Project.COREMVC.Areas.Admin.Models.PureVms.AppUser;
using Project.ENTITIES.Models;

namespace Project.COREMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        readonly RoleManager<AppRole> _roleManager;

        public RoleController(RoleManager<AppRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> GetRoles()
        {
          List<AppRole> appRoles =  await _roleManager.Roles.ToListAsync();

            List<GetRolesPureVm> getAppRoles = appRoles.Select(x => new GetRolesPureVm
            {
                ID = x.Id,
                RoleName = x.Name,
                CreatedDate = x.CreatedDate
            }).ToList();

            GetAppRolePageVm pageVm = new GetAppRolePageVm();
            pageVm.GetRolesPureVms = getAppRoles;

            return View(pageVm);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateRoleRequestModel  createRoleRequestModel)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await _roleManager.CreateAsync(new()
                {
                    Name = createRoleRequestModel.RoleName
                });

                if (result.Succeeded)
                {
                    return RedirectToAction("GetRoles");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(createRoleRequestModel);
           
        }
     
        public async Task<IActionResult> DestroyRole(int id)
        {

            AppRole role = await _roleManager.FindByIdAsync(id.ToString());
            await _roleManager.DeleteAsync(role);
            return RedirectToAction("GetRoles");
        }
       
    }
}

Project.COREMVC/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project.COREMVC.Areas.Admin.Models.PageVms.AppRole;
using Project.COREMVC.Areas.Admin.Models.PageVms.AppUser;
using Project.COREMVC.Areas.Admin.Models.PureVms.AppRole;
using Project.COREMVC.Areas.Admin.Models.PureVms.AppUser;
using Project.ENTITIES.Models;

namespace Project.COREMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        readonly UserManager<AppUser> _userManager;
        readonly RoleManager<AppRole> _roleManager;

        public UserController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {


            List<AppUser> nonAdminUsers = _userManager.Users.Where(x => !x.UserRoles.Any(x => x.Role.Name == "Admin")).ToList();

            List<AppUserPureVm> appUsers = nonAdminUsers.Select(x => new AppUserPureVm
            {
                UserName = x.UserName,
                Email = x.Email,
                ID = x.Id,
            }).ToList();

            AppUserPageVm pageVm = new()
            {
                AppUserPureVms = appUsers
            };

            return View(pageVm);
        }


        public async Task<IActionResult> AssignRole(int id)
        {
            AppUser appUser = await _userManager.Users.SingleOrDefaultAsync(x => x.Id == id);

            IList<string> userRoles = await _userManager.GetRolesAsync(appUser); // Elimize gecen kullanıcının rollerini verir

            TempData["message"] = $"Rol değiştirmek istediğiniz kullanıcının adı {appUser.UserName}";

            List<AppRole> allRoles = _roleManager.Roles.ToList(); //bütün roller

            List<AppRoleResponseModel> roles = new();


            foreach (AppRole role in allRoles)
            {
                roles.Add(new()
                {
                    RoleID = role.Id,
                    RoleName = role.Name,
                    Checked = userRoles.Contains(role.Name)
                });
            }

            AppRolePageVM aRPageVm = new()
            {
                UserID = id,
                Roles = roles
            };

            return View(aRPageVm);
        }
        [HttpPost]
        public async Task<IActionResult> AssignRole(AppRolePageVM model)
        {
            AppUser appUser = await _userManager.Users.SingleOrDefaultAsync(x => x.Id == model.UserID);
            IList<string> userRoles = await _userManager.GetRolesAsync(appUser);

            

            foreach (AppRoleResponseModel role in model.Roles)
            {
                
                if (role.Checked && !userRoles.Contains(role.RoleName))
                {
                    await _userManager.AddToRoleAsync(appUser, role.RoleName);
                   
                }

                else if (!role.Checked && userRoles.Contains(role.RoleName))
                {
                    await _userManager.RemoveFromRoleAsync(appUser, role.RoleName);
                   
                }
                
            }
            

            return RedirectToAction("Index");
        }

    }
}

Project.COREMVC/Controllers/ShoppingController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Project.BLL.Managers.Abstracts;
using Project.COMMON.Tools;
using Project.COREMVC.Areas.Admin.Models.PureVms.Category;
using Project.COREMVC.Areas.Admin.Models.PureVms.Product;
using Project.COREMVC.Models.PageVms.AppUsers;
using Project.COREMVC.Models.PageVms.OrderPageVm;
using Project.COREMVC.Models.PageVms.Product;
using Project.COREMVC.Models.PageVms.Shopping;
using Project.COREMVC.Models.PureVms.AppUsers;
using Project.COREMVC.Models.PureVms.Attribute;
using Project.COREMVC.Models.PureVms.OrderDetails;
using Project.COREMVC.Models.PureVms.Orders;
using Project.COREMVC.Models.PureVms.Products;
using Project.COREMVC.Models.PureVms.Shoppings;
using Project.COREMVC.Models.SessionServices;
using Project.COREMVC.Models.ShoppingTools;
using Project.ENTITIES.Models;
using System.Linq;
using System.Text;
using X.PagedList;

namespace Project.COREMVC.Controllers
{
    public class ShoppingController : Controller
    {
        readonly IProductManager _productManager;
        readonly ICategoryManager _categoryManager;
        readonly IOrderManager _orderManager;
        readonly IOrderDetailManager _orderDetailManager;
        readonly UserManager<AppUser> _userManager;
        readonly IHttpClientFactory _httpClientFactory;
        readonly IEntityAttributeProductManager _entityAttributeProductManager;
        readonly IEntityAttributeManager _entityAttributeManager;
        public ShoppingController(IProductManager productManager, ICategoryManager categoryManager, IOrderManager orderManager, IOrderDetailManager orderDetailManager, UserManager<AppUser> userManager, IHttpClientFactory httpClientFactory, IEntityAttributeProductManager entityAttributeProductManager, IEntityAttributeManager entityAttributeManager)
        {
            _productManager = productManager;
            _categoryManager = categoryManager;
            _orderManager = orderManager;
            _orderDetailManager = orderDetailManager;
            _userManager = userManager;
            _httpClientFactory = httpClientFactory;
            _entityAttributeProductManager = entityAttributeProductManager;
            _entityAttributeManager = entityAttributeManager;
        }

        public IActionResult Index(int? page, int? categoryID)
        {

            List<Category> categories = _categoryManager.GetActives();

            List<CategoryForShoppingPureVm> cPureVm = categories.Select(cPureVm => new CategoryForShoppingPureVm
            {
                ID = cPureVm.ID,
                CategoryName = cPureVm.CategoryName

            }).ToList();

            List<Product> products = _productManager.GetActives();

            IPagedList<ProductForShoppingPureVm> pPureVm = products.Select(pPureVm => new ProductForShoppingPureVm
            {
                ID = pPureVm.ID,
                ProductName = pPureVm.ProductName,
                UnitPrice = pPureVm.UnitPrice,
                UnitsInStock = pPureVm.UnitsInStock,
                ImagePath = pPureVm.ImagePath,
                CategoryName = pPureVm.Category.CategoryName,
                CategoryID = pPureVm.Category.ID

            }).ToPagedList();



            ShoppingPageVm sPageVm = new ShoppingPageVm();


            sPageVm.ProductForShoppingPureVms = categoryID == null ? pPureVm.ToPagedList(page ?? 1, 5) : pPureVm.Where(x => x.CategoryID == categoryID).ToPagedList(page ?? 1, 5);

            sPageVm.CategoryForShoppingPureVms = cPureVm;



            if (categoryID != null)
            {
                TempData["catID"] = categoryID;
            }




            return View(sPageVm);
        }

       
        public async Task<IActionResult> AddToCart(int id)
        {
            // Burada kısacası sepet varsa onu kullan yoksa yeniden yarat
            Cart c = GetCartFromSession("scart") == null ? new Cart() : GetCartFromSession("scart");
            CartPageVm cartPageVm = new CartPageVm();
            cartPageVm.Cart = c;


            Product productToBeAdded = await _productManager.FindAsync(id);
            ProductForShoppingPureVm pPureVm = new()
            {
                ID = productToBeAdded.ID,
                ProductName = productToBeAdded.ProductName,
                UnitPrice = productToBeAdded.UnitPrice,
                
                CategoryID = productToBeAdded.Category.ID,
                CategoryName = productToBeAdded.Category.CategoryName,
                ImagePath = productToBeAdded.ImagePath

            };


            CartItem ci = new()
            {
                ID = pPureVm.ID,
                ProductName = pPureVm.ProductName,
                UnitPrice = pPureVm.UnitPrice,
                ImagePath = pPureVm.ImagePath,
                CategoryName = pPureVm.CategoryName,
                CategoryID = pPureVm.CategoryID
            };

            cartPageVm.Cart.AddToCart(ci);


            SetCartForSession(cartPageVm.Cart);

            TempData["message"] = $"{ci.ProductName} isimli ürün sepete eklenmiştir";

            return RedirectToAction("Index", new { productToBeAdded.CategoryID });
        }

        // Bu metottada sepeti session'a eklemiş bulnmaktayız
        void SetCartForSession(Cart c)
        {
            HttpContext.Session.SetObject("scart", c);
        }

        // Cart nesnesi session da var mı yok mu onu kontrol etmesi için bu geriye değer döndüren metotu yarattık
        Cart GetCartFromSession(string key)
        {
            return HttpContext.Session.GetObject<Cart>(key);
        }


        public IActionResult CartPage()
        {
            if (GetCartFromSession("scart") == null)
            {
                TempData["message"] = "Sepetiniz su anda bos";
                return RedirectToAction("Index");
            }


            Cart c = GetCartFromSession("scart");

            CartPageVm cartPageVm = new CartPageVm();
            cartPageVm.Cart = c;
            return View(cartPageVm); 
        }


        public IActionResult DeleteFromCart(int id)
        {
            if (GetCartFromSession("scart") != null)
            {
                Cart c = GetCartFromSession("scart");


                CartPageVm cartPageVm = new CartPageVm();
                cartPageVm.Cart = c;


               cartPageVm.Cart.RemoveFromCart(id);
                SetCartForSession(cartPageVm.Cart);
                ControlCart(cartPageVm.Cart);
            }
            return RedirectToAction("CartPage");
        }

        //Cart'ın içerisindeki ürünler sıfırsa Cart'ı direkt sil
        void ControlCart(Cart c)
        {
            if (c.GetCartItems.Count == 0) HttpContext.Session.Remove("scart");
        }

        public IActionResult DecreaseFromCart(int id)
        {

            if (GetCartFromSession("scart") != null)
            {
                Cart c = GetCartFromSession("scart");
                CartPageVm cartPageVm= new CartPageVm();
                cartPageVm.Cart = c;
                cartPageVm.Cart.Decrease(id);
                SetCartForSession(cartPageVm.Cart);
                ControlCart(cartPageVm.Cart);
            }

            return RedirectToAction("CartPage");
        }
     
        public IActionResult ConfirmOrder()
        {
            return View();
        }
        [HttpPost]
        public async  Task<IActionResult> ConfirmOrder(OrderRequestPageVm orPageVm)
        {

         
            
            Cart c = GetCartFromSession("scart");
            CartPageVm cartPageVm = new CartPageVm();
            cartPageVm.Cart = c;


            orPageVm.OrderPureVm.PriceOfOrder = orPageVm.PaymentRequestPureVm.ShoppingPrice = cartPageVm.Cart.TotalPrice;


             //http://localhost:5118/

            HttpClient client = _httpClientFactory.CreateClient();
            string jsonData = JsonConvert.SerializeObject(orPageVm.PaymentRequestPureVm);
            StringContent content =new StringContent(jsonData, Encoding.UTF8,"application/json");
           HttpResponseMessage responseMessage =  await client.PostAsync("http://localhost:5118/api/Transaction", content);


            if (responseMessage.IsSuccessStatusCode)
            {
                if (User.Identity.IsAuthenticated)
                {
                    AppUser appUser = await _userManager.FindByNameAsync(User.Identity.Name);

                    orPageVm.OrderPureVm.AppUserID = appUser.Id;
                    orPageVm.OrderPureVm.Email = appUser.Email;
                    orPageVm.OrderPureVm.NameDescription = appUser.UserName;

                }

                Order order = new()
                {
                    Email = orPageVm.OrderPureVm.Email,
                    NameDescription = orPageVm.OrderPureVm.NameDescription,
                    AppUserID = orPageVm.OrderPureVm.AppUserID,
                    PriceOfOrder = orPageVm.OrderPureVm.PriceOfOrder,
                    ShippingAddress = orPageVm.OrderPureVm.ShippingAddress,
                    ID = orPageVm.OrderPureVm.ID
                };
                await _orderManager.AddAsync(order);

                
                string urunIsimleri = "";
                decimal ürünToplamFiyat = 0;
                foreach (CartItem item in cartPageVm.Cart.GetCartItems)
                {
                    OrderDetail orderDetail = new()
                    {
                        OrderID = order.ID,
                        ProductID = item.ID,
                        Quantity = item.Amount,
                        UnitPrice = item.UnitPrice
                    };

                    Product product = await _productManager.FindAsync(item.ID);
                        product.UnitsInStock -= item.Amount;
                    await _productManager.UpdateAsync(product);

                    await _orderDetailManager.AddAsync(orderDetail);
                    urunIsimleri += $" {item.ProductName} x{item.Amount} tane,";
                    

Project.COREMVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="icon" href="~/OuterImages/Favicon.png">

    <title>Uygun Al ADMİN</title>

    <!-- Bootstrap core CSS -->
    <link href="~/OuterTools/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/OuterTools/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="~/OuterTools/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />

    <link href="~/OuterTools/assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/OuterTools/assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>


    <!-- Custom styles for this template -->
    <link href="~/OuterTools/css/style.css" rel="stylesheet">
    <link href="~/OuterTools/css/style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <section id="container" class="">
        <!--header start-->
        <header class="header white-bg">
            <div class="sidebar-toggle-box">
                <div data-original-title="Toggle Navigation" data-placement="right" class="icon-reorder tooltips"></div>
            </div>
            <!--logo start-->
            <a asp-area="" asp-action="Index" asp-controller="Shopping" class="logo">Uygun<span >Al</span></a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
                <!--  notification start -->
                <ul class="nav top-menu">
                    <!-- settings start -->
                   
                    <!-- settings end -->
                    <!-- inbox dropdown start-->
                   
                    <!-- inbox dropdown end -->
                    <!-- notification dropdown start--> 
                    
                    <!-- notification dropdown end -->
                </ul>
            </div>
            <div class="top-nav ">
                <ul class="nav pull-right top-menu">
                   
                    <!-- user login dropdown start-->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <img alt="" src="img/avatar1_small.jpg">
                            <span class="username">
                                <img alt="" src="~/OuterImages/AnonimFoto.jpg">
                                @(User.Identity.Name ?? "Kullanıcı")
                            </span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu extended logout">
                            <div class="log-arrow-up"></div>
                            
                           
                            </ul>
                        </ul>
                    </li>
                    <!-- user login dropdown end -->
                </ul>
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <li>
                        <a asp-area="" asp-controller="Shopping" asp-action="Index">
                            <i class="icon-shopping-cart"></i>
                            <span>Alışveriş sayfası</span>
                        </a>
                    </li>


                    <li>
                        <a asp-area="" asp-action="Logout" asp-controller="Home">
                            <i class="icon-warning-sign"></i>
                            <span>Çıkış yap</span>
                        </a>
                    </li>

                    <li>
                        <a asp-action="Index" asp-controller="User">
                            <i class="icon-user"></i>
                            <span>Kullanıcıların listesi</span>
                        </a>
                    </li>
                    <li>
                        <a asp-action="GetRoles" asp-controller="Role">
                            <i class="icon-plus"></i>
                            <span>Rol ekle</span>
                        </a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Order">
                            <i class="glyphicon glyphicon-th-large"></i>
                            <span>Siparişler</span>
                        </a>
                    </li>
                  
                    <li class="sub-menu">
                        <a asp-action="GetCategories" asp-controller="Category">
                            
                            <i class="icon-bookmark"></i>
                            <span> Kategoriler</span>
                        </a>
                          
                        
                        <ul class="sub">
                            <li><a asp-action="GetCategories" asp-controller="Category" > Kategorileri listele</a></li>
                            <li><a asp-action="CreateCategory" asp-controller="Category" > Kategori ekle</a></li>
                           
                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a asp-action="GetProducts" asp-controller="Product">

                            <i class="icon-tags"></i>
                            <span> Ürünler</span>
                        </a>


                        <ul class="sub">
                            <li><a asp-action="GetProducts" asp-controller="Product"> Ürünleri listele</a></li>
                            <li><a asp-action="CreateProduct" asp-controller="Product"> Ürün  ekle</a></li>

                        </ul>
                    </li>
                    <!--multi level menu end-->

                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
               @RenderBody()
            </section>
        </section>
        <!--main content end-->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                2024 &copy; UygunAl by VectorLab.
                <a href="#" class="go-top">
                    <i class="icon-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <!--<script src="js/jquery.js"></script>-->
    <script type="text/javascript" language="javascript" src="~/OuterTools/assets/advanced-datatable/media/js/jquery.js"></script>
    <script src="~/OuterTools/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="~/OuterTools/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/OuterTools/js/jquery.scrollTo.min.js"></script>
    <script src="~/OuterTools/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/OuterTools/js/respond.min.js"></script>
    <script type="text/javascript" language="javascript" src="~/OuterTools/assets/advanced-datatable/media/js/jquery.dataTables.js"></script>


    <!--common script for all pages-->
    <script src="~/OuterTools/js/common-scripts.js"></script>

    <script type="text/javascript">
        /* Formating function for row details */
        function fnFormatDetails ( oTable, nTr )
        {
            var aData = oTable.fnGetData( nTr );
            var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
            sOut += '<tr><td>Rendering engine:</td><td>'+aData[1]+' '+aData[4]+'</td></tr>';
            sOut += '<tr><td>Link to source:</td><td>Could provide a link here</td></tr>';
            sOut += '<tr><td>Extra info:</td><td>And any further details here (images etc)</td></tr>';
            sOut += '</table>';

            return sOut;
        }

        $(document).ready(function() {
            /*
             * Insert a 'details' column to the table
             */
            var nCloneTh = document.createElement( 'th' );
            var nCloneTd = document.createElement( 'td' );
           
            nCloneTd.className = "center";

            $('#hidden-table-info thead tr').each( function () {
                this.insertBefore( nCloneTh, this.childNodes[0] );
            } );

            $('#hidden-table-info tbody tr').each( function () {
                this.insertBefore(  nCloneTd.cloneNode( true ), this.childNodes[0] );
            } );

            /*
             * Initialse DataTables, with no sorting on the 'details' column
             */
            var oTable = $('#hidden-table-info').dataTable( {
                "aoColumnDefs": [
                    { "bSortable": false, "aTargets": [ 0 ] }
                ],
                "aaSorting": [[1, 'asc']]
            });

            /* Add event listener for opening and closing details
             * Note that the indicator for showing which row is open is not controlled by DataTables,
             * rather it is done here
             */
            $('#hidden-table-info tbody td img').live('click', function () {
                var nTr = $(this).parents('tr')[0];
                if ( oTable.fnIsOpen(nTr) )
                {
                    /* This row is already open - close it */
                    this.src = "/OuterTools/assets/advanced-datatable/examples/examples_support/details_open.png";
                    oTable.fnClose( nTr );
                }
                else
                {
                    /* Open this row */
                    this.src = "/OuterTools/assets/advanced-datatable/examples/examples_support/details_close.png";
                    oTable.fnOpen( nTr, fnFormatDetails(oTable, nTr), 'details' );
                }
            } );
        } );
    </script>


</body>
</html>