Project.COREMVC/Models/PureVms/Attribute/AttributePureVm.cs
namespace Project.COREMVC.Models.PureVms.Attribute
{
    public class AttributePureVm
    {
        public string AttributeName { get; set; }
        public string ValueName { get; set; }
    }
}

Project.COREMVC/Areas/Admin/Controllers/AttributeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Project.BLL.Managers.Abstracts;
using Project.BLL.Managers.Concretes;
using Project.COREMVC.Areas.Admin.Models.PageVms.EntityAttribute;
using Project.COREMVC.Areas.Admin.Models.PureVms.EntityAttribute;
using Project.ENTITIES.Models;
using System;

namespace Project.COREMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AttributeController : Controller
    {
        readonly IEntityAttributeManager _entityAttributeManager;
        readonly IEntityAttributeProductManager _entityAttributeProductManager;
        readonly IProductManager _productManager;

        public AttributeController(IEntityAttributeManager entityAttributeManager, IEntityAttributeProductManager entityAttributeProductManager, IProductManager productManager)
        {
            _entityAttributeManager = entityAttributeManager;
            _entityAttributeProductManager = entityAttributeProductManager;
            _productManager = productManager;
        }


        public async Task<IActionResult> GetAttributeProduct(int id)
        {


            List<EntityAttributeProduct> eAProduct = _entityAttributeProductManager.Where(x => x.ProductID == id).ToList();

            List<EntityAttribute> eAttributes = _entityAttributeManager.GetAll();


            List<EntityAttribute> newEAttributess = eAttributes.Join(eAProduct,
           eAttr => eAttr.ID,  // eAttributes'taki ID
           eProd => eProd.EntityAttributeID,  // eAProducts'taki EntityAttributeID
           (eAttr, eProd) => eAttr)  // Eşleşen eAttributes nesnelerini al
                                     .ToList();

            List<EntityAttributePureVm> entityAttributePureVms = newEAttributess.Select(x => new EntityAttributePureVm
            {
                AttributeName = x.AttributeName,
                ID = x.ID
            }).ToList();

            List<EntityAttributeProductPureVm> entityAttributeProductPureVms = eAProduct.Select(x => new EntityAttributeProductPureVm
            {
                Value = x.Value,
                ProductID = x.ProductID,
                EntityAttributeID = x.EntityAttributeID
            }).ToList();


            EntityAttributePageVm pageVm = new EntityAttributePageVm();
            pageVm.EntityAttributeProductPureVms = entityAttributeProductPureVms;
            pageVm.EntityAttributePureVms = entityAttributePureVms;

            if ( pageVm.EntityAttributePureVms.Count ==0 )
            {
                
                return RedirectToAction("AttributeProduct", new { id });
            }


            return View(pageVm);




        }


        public async Task<IActionResult> AttributeProduct(int id)
        {
            EntityAttributeCreatePureVm pureVm = new()
            {
                ProductID = id,

            };
            EntityAttributeCreatePageVm pageVm = new EntityAttributeCreatePageVm();
            pageVm.EntityAttributeCreatePureVm = pureVm;
            return View(pageVm);
        }


        [HttpPost]
        public async Task<IActionResult> AttributeProduct(EntityAttributeCreatePageVm pageVm)
        {

            EntityAttribute entityAttribute = new();

            if ( await _entityAttributeManager.AnyAsync(x=> x.AttributeName == pageVm.EntityAttributeCreatePureVm.AttributeName))
            {

                 entityAttribute =  _entityAttributeManager.FirstOrDefault(x => x.AttributeName == pageVm.EntityAttributeCreatePureVm.AttributeName);
               
            }
            else
            {

                entityAttribute.AttributeName = pageVm.EntityAttributeCreatePureVm.AttributeName;
                
                await _entityAttributeManager.AddAsync(entityAttribute);
               
            }
            if (await _entityAttributeProductManager.AnyAsync(x => x.ProductID == pageVm.EntityAttributeCreatePureVm.ProductID && x.EntityAttributeID == entityAttribute.ID))
            {
                TempData["message"] = $"{entityAttribute.AttributeName} isimli özellik bu üründe bulunmakadır ";
            }
            else
            {
                EntityAttributeProduct entityAttributeProduct = new()
                {
                    EntityAttributeID = entityAttribute.ID,
                    Value = pageVm.EntityAttributeCreatePureVm.Value,
                    ProductID = pageVm.EntityAttributeCreatePureVm.ProductID
                };
                await _entityAttributeProductManager.AddAsync(entityAttributeProduct);
                TempData["message"] = $"{entityAttributeProduct.ProductID} ID'li ürüne özellik eklenmiştir";
            }
           




            return View(pageVm);
        }

        public async Task<IActionResult> DestroyAttribute(int productId, int attributeId)
        {

            EntityAttributeProduct? entityAttributeProduct = _entityAttributeProductManager.Where(e => e.ProductID == productId && e.EntityAttributeID == attributeId).SingleOrDefault();

            if (entityAttributeProduct != null)
            {
                _entityAttributeProductManager.Delete(entityAttributeProduct);
                _entityAttributeProductManager.Destroy(entityAttributeProduct);
            }

            // EntityAttribute'yu bulun ve silin
          
                TempData["message"] = $"{entityAttributeProduct.ID} ID'li özellik başarıyla yok edildi";
            
           

            return RedirectToAction("GetProducts", "Product");

        }

        public async Task<IActionResult> UpdateAttribute(int productId, int attributeId)
        {
            EntityAttributeProduct? entityAttributeProduct = _entityAttributeProductManager.Where(e => e.ProductID == productId && e.EntityAttributeID == attributeId).SingleOrDefault();

            UpdateAttributeProductPureVm aPPureVm = new UpdateAttributeProductPureVm()
            {
                EntityAttributeID = entityAttributeProduct.EntityAttributeID,
                ProductID = productId,
                Value = entityAttributeProduct.Value
            };

            EntityAttribute entityAttribute = await _entityAttributeManager.FindAsync(attributeId);

            UpdateAttributePureVm aPureVm = new()
            {
                AttributeID = entityAttribute.ID,
                AttributeName = entityAttribute.AttributeName
            };


            UpdateAttributeProductPageVm updateAttributeProductPageVm = new()
            {
                UpdateAttributeProductPureVm = aPPureVm,
                UpdateAttributePureVm = aPureVm
            };


            return View(updateAttributeProductPageVm);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateAttribute(UpdateAttributeProductPageVm pageVm)
        {

            // EntityAttribute güncelleme
            EntityAttribute entityAttribute = await _entityAttributeManager.FindAsync(pageVm.UpdateAttributePureVm.AttributeID);

            entityAttribute.AttributeName = pageVm.UpdateAttributePureVm.AttributeName;
            await _entityAttributeManager.UpdateAsync(entityAttribute);

            EntityAttributeProduct entityAttributeProduct = new EntityAttributeProduct();
            entityAttributeProduct.EntityAttributeID = pageVm.UpdateAttributePureVm.AttributeID;
            entityAttributeProduct.ProductID = pageVm.UpdateAttributeProductPureVm.ProductID;
            entityAttributeProduct.Value = pageVm.UpdateAttributeProductPureVm.Value;

            EntityAttributeProduct originalAttribute = _entityAttributeProductManager.Where(x => x.ProductID == entityAttributeProduct.ProductID && x.EntityAttributeID == entityAttributeProduct.EntityAttributeID).FirstOrDefault();
            _entityAttributeProductManager.UpdateForJunction(entityAttributeProduct , originalAttribute);

            TempData["message"] = $"{originalAttribute.ProductID} ID'li ürünün {originalAttribute.EntityAttributeID } ID'li özelliği değiştirilmiştir";



           


            return RedirectToAction("GetProducts", "Product");
        }
    }
}

Project.COREMVC/Areas/Admin/Views/Attribute/AttributeProduct.cshtml
@model EntityAttributeCreatePageVm


<h2> Ürüne Özellik ekleyebilirsiniz </h2>

<h1>
    @TempData["message"]
</h1>


<form asp-action="AttributeProduct" asp-controller="Attribute" method="post" class="p-3 w-75 m-auto">
   
    
  

    <input type="hidden" asp-for="EntityAttributeCreatePureVm.ProductID" />

   

    <div class="form-group">
        <label>
            <span asp-validation-for="EntityAttributeCreatePureVm.AttributeName" class="text-danger">

            </span>
        </label>
        <input asp-for="EntityAttributeCreatePureVm.AttributeName" class="form-control" placeholder="Özellik ismi giriniz" />
    </div>


    <div class="form-group">
        <label>
            <span asp-validation-for="EntityAttributeCreatePureVm.Value" class="text-danger">

            </span>
        </label>
        <input asp-for="EntityAttributeCreatePureVm.Value" class="form-control" placeholder="Değerini giriniz" />
    </div>

    <div class="form-group">
        <button class="btn btn-primary"> Özellik ekle</button>

    </div>
   
        <a asp-controller="Attribute" asp-action="GetAttributeProduct" asp-route-id="@Model.EntityAttributeCreatePureVm.ProductID" class="btn btn-success">Özellikleri gör</a>
   

</form>

Project.COREMVC/Areas/Admin/Views/Attribute/GetAttributeProduct.cshtml
@model EntityAttributePageVm
<h1>
    @TempData["message"]
</h1>



    <form>


        @for (int i = 0; i < Model.EntityAttributePureVms.Count; i++)
        {
            <input type="hidden" asp-for="EntityAttributePureVms[i].ID" />
        }

        @{
            int productId = Model.EntityAttributeProductPureVms.FirstOrDefault().ProductID ;
        }

        <input type="hidden" asp-for="EntityAttributeProductPureVms[0].ProductID" />

       

        <a asp-action="AttributeProduct" asp-controller="Attribute" asp-route-id="@productId" class="btn btn-primary"><strong>Özellik eklemek için tıkla</strong> </a>
        <a asp-action="GetProducts" asp-controller="Product" class="btn btn-primary" ><strong >Ürünleri görmek için tıkla</strong> </a>

        <h1>Özelliker listesi</h1>
        <div class="row">
            <div class="col-md-12">
                <section class="panel tasks-widget">
                    <header class="panel-heading">
                        @for (int i = 0; i < Model.EntityAttributeProductPureVms.Count; i++)
                        {
                            <span>@Model.EntityAttributeProductPureVms[i].ProductID</span> <span>ID'li ürünün özelikleri</span>
                            break;
                        }
                    </header>
                    <div class="panel-body">

                        <div class="task-content">

                            <ul class="task-list">
                            @for (int i = 0; i < Model.EntityAttributePureVms.Count; i++ )
                                {
                                    <li style="border-bottom: 1px solid #ddd; padding: 3px 0;">
                                        <div class="task-title" style="display: flex; align-items: center; justify-content: space-between;">
                                            <div>
                                                <strong>ID =</strong>
                                                <span class="task-title-sp">
                                                    @Model.EntityAttributePureVms[i].ID
                                                </span>
                                                <strong>Özellik ismi =</strong>
                                                <span class="task-title-sp">
                                                    @Model.EntityAttributePureVms[i].AttributeName
                                                </span>
                                            @for (int j = 0; j < Model.EntityAttributeProductPureVms.Count; j++)
                                            {
                                   
                                        
                                            
                                               
                                                
                                                
                                                <strong>Değeri =</strong>
                                                <span class="task-title-sp">
                                                                @(Model.EntityAttributeProductPureVms[i].Value ?? "null")
                                                </span>
                                            
                                                       
                                       
                                                
                                                break;

                                            }
                                            </div>
                                            <div>
                                                <a asp-controller="Attribute" asp-action="UpdateAttribute"
                                                   asp-route-productId="@Model.EntityAttributeProductPureVms[i].ProductID"
                                                   asp-route-attributeId="@Model.EntityAttributePureVms[i].ID" class="btn btn-danger"><i class="icon-pencil"></i></a>
                                                <a asp-controller="Attribute" asp-action="DestroyAttribute"
                                                   asp-route-productId="@Model.EntityAttributeProductPureVms[i].ProductID"
                                                   asp-route-attributeId="@Model.EntityAttributePureVms[i].ID" class="btn btn-danger"><i class="icon-trash"></i></a>
                                            </div>
                                        </div>
                                    </li>
                             }
                           
                                </li>
                            
                            </ul>
                        </div>


                    </div>
                </section>
            </div>
        </div>



    </form>
   


           
        

     




   

Project.COREMVC/Areas/Admin/Views/Attribute/UpdateAttribute.cshtml
@model UpdateAttributeProductPageVm

<h1>
    @TempData["message"]
</h1>


<form asp-action="UpdateAttribute" asp-controller="Attribute" method="post" class="p-3 w-75 m-auto">


   

    <input type="hidden" asp-for="UpdateAttributeProductPureVm.ProductID" />
    <input type="hidden" asp-for="UpdateAttributeProductPureVm.EntityAttributeID" />
    <input type="hidden" asp-for="UpdateAttributePureVm.AttributeID" />



    <div class="form-group">
        <label>
            <span asp-validation-for="UpdateAttributePureVm.AttributeName" class="text-danger">

            </span>
        </label>
        <input asp-for="UpdateAttributePureVm.AttributeName" class="form-control" placeholder="Özellik ismi giriniz" />
    </div>


    <div class="form-group">
        <label>
            <span asp-validation-for="UpdateAttributeProductPureVm.Value" class="text-danger">

            </span>
        </label>
        <input asp-for="UpdateAttributeProductPureVm.Value" class="form-control" placeholder="Değerini giriniz" />
    </div>

    <div class="form-group">
        <button class="btn btn-primary"> Özelliği güncelle</button>

    </div>
    <a asp-controller="Attribute" asp-action="GetAttributeProduct" asp-route-id="@Model.UpdateAttributeProductPureVm.ProductID" class="btn btn-success">Özellikleri gör</a>
  

</form>